services:
  - type: web
    name: job-recommendation-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 3000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
