import { QuestionItem } from '../types/question';

/**
 * Related questions organized by tags
 */
export const RELATED_QUESTIONS_BY_TAG: Record<string, QuestionItem[]> = {
  "REST": [
    {
      id: 'rest-1',
      question: 'Explain the difference between PUT and PATCH methods in RESTful APIs',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1586,
      tags: ['API', 'REST', 'HTTP'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'rest-2',
      question: 'What are the key principles of RESTful API design?',
      category: 'backend',
      difficulty: 'Easy',
      answeredCount: 2105,
      tags: ['API', 'REST', 'Architecture'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'rest-3',
      question: 'How would you implement versioning in a REST API?',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1248,
      tags: ['API', 'REST', 'Versioning'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'rest-4',
      question: 'Compare REST and GraphQL. When would you choose one over the other?',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1753,
      tags: ['API', 'REST', 'GraphQL', 'Architecture'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'rest-5',
      question: 'Explain how to handle authentication in RESTful APIs',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1896,
      tags: ['API', 'REST', 'Security', 'Authentication'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  "React": [
    {
      id: 'react-1',
      question: 'Explain the virtual DOM in React and how it improves performance',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 2340,
      tags: ['React', 'Performance', 'Virtual DOM'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'react-2',
      question: 'What are React Hooks? Explain useState and useEffect',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 2760,
      tags: ['React', 'Hooks', 'useState', 'useEffect'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'react-3',
      question: 'How does React Router work? Implement a basic routing setup',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1870,
      tags: ['React', 'Routing', 'React Router'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'react-4',
      question: 'Explain React context API and when to use it instead of prop drilling',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1930,
      tags: ['React', 'Context API', 'State Management'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'react-5',
      question: 'What is the importance of keys in React lists?',
      category: 'frontend',
      difficulty: 'Easy',
      answeredCount: 2150,
      tags: ['React', 'Lists', 'Performance'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  "JavaScript": [
    {
      id: 'js-1',
      question: 'Explain event bubbling and capturing in JavaScript',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1685,
      tags: ['JavaScript', 'Events', 'DOM'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'js-2',
      question: 'Implement a debounce function in JavaScript',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1842,
      tags: ['JavaScript', 'Performance', 'Optimization'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'js-3',
      question: 'Explain Promises and async/await in JavaScript',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 2540,
      tags: ['JavaScript', 'Promises', 'Async'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'js-4',
      question: 'Describe the prototypal inheritance model in JavaScript',
      category: 'frontend',
      difficulty: 'Hard',
      answeredCount: 1430,
      tags: ['JavaScript', 'Inheritance', 'OOP'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'js-5',
      question: 'How does hoisting work in JavaScript?',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1740,
      tags: ['JavaScript', 'Fundamentals', 'Scope'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  "System Design": [
    {
      id: 'sd-1',
      question: 'Design a URL shortening service like bit.ly',
      category: 'system-design',
      difficulty: 'Medium',
      answeredCount: 1490,
      tags: ['System Design', 'URL Shortener', 'Scalability'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'sd-2',
      question: 'How would you design a distributed cache?',
      category: 'system-design',
      difficulty: 'Hard',
      answeredCount: 1280,
      tags: ['System Design', 'Caching', 'Distributed Systems'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'sd-3',
      question: 'Design a notification service for a social media platform',
      category: 'system-design',
      difficulty: 'Medium',
      answeredCount: 1340,
      tags: ['System Design', 'Notifications', 'Scalability'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'sd-4',
      question: 'How would you design a rate limiting system?',
      category: 'system-design',
      difficulty: 'Medium',
      answeredCount: 1450,
      tags: ['System Design', 'Rate Limiting', 'API'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'sd-5',
      question: 'Design a data storage system for time-series data',
      category: 'system-design',
      difficulty: 'Hard',
      answeredCount: 980,
      tags: ['System Design', 'Databases', 'Time Series'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  "Algorithms": [
    {
      id: 'algo-1',
      question: 'Implement a function to check if a binary tree is balanced',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1985,
      tags: ['Tree', 'Recursion', 'Binary Tree', 'Algorithms'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'algo-2',
      question: 'Find the longest substring without repeating characters',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1875,
      tags: ['String', 'Sliding Window', 'Algorithms'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'algo-3',
      question: 'Implement a function to detect a cycle in a linked list',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1690,
      tags: ['Linked List', 'Two Pointer', 'Algorithms'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'algo-4',
      question: 'Implement merge sort algorithm',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1790,
      tags: ['Sorting', 'Divide and Conquer', 'Algorithms'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'algo-5',
      question: 'Design an algorithm to find the kth largest element in an array',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1580,
      tags: ['Array', 'Heap', 'Quickselect', 'Algorithms'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
  ],
  "Behavioral": [
    {
      id: 'behav-1',
      question: 'Describe a situation where you had to handle a difficult team conflict and how you resolved it',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 3421,
      tags: ['Teamwork', 'Conflict', 'Communication', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'behav-2',
      question: 'Tell me about a time when you had to meet a tight deadline',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 2980,
      tags: ['Time Management', 'Stress', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'behav-3',
      question: 'Describe a situation where you showed leadership skills',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 2745,
      tags: ['Leadership', 'Initiative', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'behav-4',
      question: 'Give an example of a time when you had to make a difficult decision',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 2630,
      tags: ['Decision Making', 'Problem Solving', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'behav-5',
      question: 'Tell me about a time when you received critical feedback and how you responded to it',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 2410,
      tags: ['Feedback', 'Growth', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
};

/**
 * Related questions organized by category
 */
export const RELATED_QUESTIONS_BY_CATEGORY: Record<string, QuestionItem[]> = {
  frontend: [
    {
      id: 'fe-1',
      question: 'Explain CSS Grid and how it differs from Flexbox',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1845,
      tags: ['CSS', 'Layout', 'Grid', 'Flexbox'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'fe-2',
      question: 'How does browser rendering work?',
      category: 'frontend',
      difficulty: 'Hard',
      answeredCount: 1432,
      tags: ['Browser', 'Performance', 'Rendering'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'fe-3',
      question: 'Compare and contrast controlled vs uncontrolled components in React',
      category: 'frontend',
      difficulty: 'Medium',
      answeredCount: 1670,
      tags: ['React', 'Forms', 'Components'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  backend: [
    {
      id: 'be-1',
      question: 'What are ACID properties in database transactions?',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1670,
      tags: ['Database', 'Transactions', 'ACID'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'be-2',
      question: 'Explain the concept of middleware in Express.js',
      category: 'backend',
      difficulty: 'Medium',
      answeredCount: 1450,
      tags: ['Node.js', 'Express', 'Middleware'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'be-3',
      question: 'How would you handle database migrations in a production environment?',
      category: 'backend',
      difficulty: 'Hard',
      answeredCount: 1230,
      tags: ['Database', 'Migrations', 'DevOps'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  'system-design': [
    {
      id: 'sd-1',
      question: 'Design a URL shortening service like bit.ly',
      category: 'system-design',
      difficulty: 'Medium',
      answeredCount: 1490,
      tags: ['System Design', 'URL Shortener', 'Scalability'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'sd-2',
      question: 'How would you design a distributed cache?',
      category: 'system-design',
      difficulty: 'Hard',
      answeredCount: 1280,
      tags: ['System Design', 'Caching', 'Distributed Systems'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  'data-structures': [
    {
      id: 'ds-1',
      question: 'Implement a trie data structure and explain its applications',
      category: 'data-structures',
      difficulty: 'Hard',
      answeredCount: 1190,
      tags: ['Trie', 'Data Structures', 'String'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
    {
      id: 'ds-2',
      question: 'Explain the differences between BFS and DFS traversals',
      category: 'data-structures',
      difficulty: 'Medium',
      answeredCount: 1760,
      tags: ['Graphs', 'Trees', 'Traversal'],
      isBookmarked: false,
      isCompleted: false,
    },
  ],
  behavioral: [
    {
      id: 'behav-1',
      question: 'Describe a situation where you had to handle a difficult team conflict and how you resolved it',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 3421,
      tags: ['Teamwork', 'Conflict', 'Communication', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
    },
    {
      id: 'behav-2',
      question: 'Tell me about a time when you had to meet a tight deadline',
      category: 'behavioral',
      difficulty: 'Medium',
      answeredCount: 2980,
      tags: ['Time Management', 'Stress', 'Behavioral'],
      isBookmarked: false,
      isCompleted: false,
      hasHints: true,
    },
  ],
};